export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const AGGREGATE_SUCCESS = 'AGGREGATE_SUCCESS'
export const AGGREGATE_FAILURE = 'AGGREGATE_FAILURE'
