export const TYPES = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  AGGREGATE_SUCCESS: 'AGGREGATE_SUCCESS',
  AGGREGATE_FAILURE: 'AGGREGATE_FAILURE',
}
